name: Build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Run build
        run: bash ./.github/scripts/build.sh
      - name: Run tests
        run: bash ./tests/start.sh
      - name: Run vimrc tests
        run: bash ./tests/dependencies/vimrc/test.sh
